version: '3.8'
services:
  lukas2023-web:
    image: php:8.1-apache
    container_name: lukas2023-web
    volumes:
      - ./src:/var/www/html/
      - ./php-conf/:/usr/local/etc/php/conf.d/
    ports:
      - 80:80